services:
  app_ac_citas:
    build: ./backend
    container_name: app_ac_citas
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/php-dev.ini:/usr/local/etc/php/conf.d/99-dev.ini
    command: >
      bash -c "chown -R www-data:www-data writable && apache2-foreground"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_ac_citas
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ac_citas_db
      MYSQL_USER: ac_user
      MYSQL_PASSWORD: secret
      TZ: America/Bogota
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/0-init.sql
    ports:
      - "3307:3306"

  whatsapp:
    build: ./whatsapp         # carpeta con Dockerfile y código
    container_name: whatsapp_reminder
    environment:
      - TZ=America/Bogota
    volumes:
      - ./whatsapp/sessions:/usr/src/app/.wwebjs_auth   # guarda sesión
    ports:
      - "8090:8080"           # expone endpoint REST en el host
    restart: unless-stopped
    shm_size: '256m'
    depends_on:
      - db                    # (si necesitas la BD, de otro modo quítalo)

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma_ac_citas
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 16M
    ports:
      - "5051:80"
    depends_on:
      - db

volumes:
  db_data:
